[package]
name = "darkhorse-adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
autotests = false

[dependencies]
rustls-pki-types.workspace = true
lettre.workspace = true
darkhorse-domain.workspace = true
darkhorse-application.workspace = true
axum.workspace = true
envbind.workspace = true
restqs.workspace = true
serde.workspace = true
serde_json.workspace = true
tower-http.workspace = true
url.workspace = true
sqlx.workspace = true
uuid.workspace = true
argon2.workspace = true
getrandom.workspace = true
zeroize.workspace = true
tokio.workspace = true
rpassword.workspace = true
redis.workspace = true
percent-encoding.workspace = true
sha2.workspace = true
hmac.workspace = true
aws-lc-rs.workspace = true
base64.workspace = true

[dev-dependencies]
tower.workspace = true
ring.workspace = true

[[test]]
name = "postgres"
path = "tests/integration/postgres.rs"
required-features = ["postgres-tests"]

[features]
email-tests = []
benchmark-profiling = []
postgres-tests = []
redis-tests = []

[[test]]
name = "redis"
path = "tests/integration/redis.rs"
required-features = ["redis-tests"]

[[test]]
name = "limiter"
path = "tests/integration/limiter.rs"
required-features = ["redis-tests"]

[lints]
workspace = true

[[test]]
name = "email"
path = "tests/integration/email.rs"
required-features = ["email-tests"]
