[package]
name = "darkhorse-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
autotests = false

[dependencies]
darkhorse-adapters.workspace = true
darkhorse-application.workspace = true
axum.workspace = true
envbind.workspace = true
tokio.workspace = true

[features]
benchmark-profiling = ["darkhorse-adapters/benchmark-profiling"]

[lints]
workspace = true
