bind 0.0.0.0
port 0
tls-port 6379
tls-cert-file /run/secrets/cache_cert
tls-key-file /run/secrets/cache_key
tls-ca-cert-file /run/secrets/ca
tls-auth-clients no
protected-mode yes
aclfile /run/secrets/cache_acl
maxmemory 64mb
maxmemory-policy allkeys-lru
maxclients 128
timeout 60
tcp-keepalive 30
save ""
appendonly no
dir /data
loglevel warning
