[database]
url = "https://github.com/RustSec/advisory-db.git"
fetch = true
stale = false

[advisories]
ignore = []
informational_warnings = ["unmaintained", "unsound", "notice"]

[output]
deny = ["warnings"]
quiet = false
