bind 0.0.0.0
port 6379
protected-mode yes
aclfile /run/redis/users.acl
maxmemory 64mb
maxmemory-policy noeviction
maxclients 128
timeout 60
tcp-keepalive 30
save ""
appendonly yes
appendfsync always
dir /data
loglevel warning
